{
  "openapi": "3.0.0",
  "info": {
    "description": "Welcome to the autogenerated documentation & test tool for Avaza's API. <br/><br/><strong>API Security & Authentication</strong><br/>Authentication options include OAuth2 Implicit and Authorization Code flows, and Personal Access Token. All connections should be encrypted over SSL/TLS <br/><br/>You can set up and manage your api authentication credentials from within your Avaza account. (requires Administrator permissions on your Avaza account).<br/><br/> OAuth2 Authorization[...]",
    "title": "Avaza API Documentation",
    "version": "v1",
    "x-jentic-source-url": "https://raw.githubusercontent.com/jentic/jentic-public-apis/refs/heads/main/apis/openapi/avaza.com/main/v1/openapi.json",
    "contact": {
      "name": "API Support"
    }
  },
  "servers": [
    {
      "url": "https://api.avaza.com/"
    }
  ],
  "paths": {
    "/ScheduleSeries/AddBooking": {
      "post": {
        "security": [
          {
            "oauth2": [
              "write_schedule"
            ]
          }
        ],
        "tags": [
          "ScheduleSeries"
        ],
        "operationId": "ScheduleSeries_AddBooking",
        "summary": "Create new Schedule Booking",
        "description": "Create new Schedule Booking"
      }
    },
    "/ScheduleSeries/AddLeave": {
      "post": {
        "security": [
          {
            "oauth2": [
              "write_schedule"
            ]
          }
        ],
        "tags": [
          "ScheduleSeries"
        ],
        "operationId": "ScheduleSeries_AddLeave",
        "summary": "Create new Leave Booking",
        "description": "Create new Leave Booking"
      }
    },
    "/ScheduleSeries/EditBooking": {
      "put": {
        "security": [
          {
            "oauth2": [
              "write_schedule"
            ]
          }
        ],
        "tags": [
          "ScheduleSeries"
        ],
        "operationId": "ScheduleSeries_EditBooking",
        "summary": "Edit Booking",
        "description": "Edit Booking"
      }
    },
    "/ScheduleSeries/EditLeave": {
      "put": {
        "security": [
          {
            "oauth2": [
              "write_schedule"
            ]
          }
        ],
        "tags": [
          "ScheduleSeries"
        ],
        "operationId": "ScheduleSeries_EditLeave",
        "summary": "Edit Leave Booking",
        "description": "Edit Leave Booking"
      }
    },
    "/api/Account": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_account"
            ]
          }
        ],
        "tags": [
          "Account"
        ],
        "operationId": "Account_Get",
        "summary": "Account Details",
        "description": "Account Details"
      }
    },
    "/api/Bill": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ],
        "tags": [
          "Bill"
        ],
        "description": "TransactionStatusCode values are: \"Draft\", \"Verified\", \"Late\", \"Paid\", \"Partial\", \"Void\"",
        "operationId": "Bill_Get",
        "summary": "Gets list of Bills"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "write_financials"
            ]
          }
        ],
        "tags": [
          "Bill"
        ],
        "operationId": "Bill_Post",
        "summary": "Create a new draft Bill",
        "description": "Create a new draft Bill"
      }
    },
    "/api/Bill/{id}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ],
        "tags": [
          "Bill"
        ],
        "operationId": "Bill_GetByID",
        "summary": "Gets a Bill by Bill ID",
        "description": "Gets a Bill by Bill ID"
      }
    },
    "/api/BillPayment": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ],
        "tags": [
          "BillPayment"
        ],
        "operationId": "BillPayment_Get",
        "summary": "Gets list of Bill Payments",
        "description": "Gets list of Bill Payments"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "write_financials"
            ]
          }
        ],
        "tags": [
          "BillPayment"
        ],
        "operationId": "BillPayment_Post",
        "summary": "Create new Bill Payment and optionally assign payment allocations to Bills",
        "description": "Create new Bill Payment and optionally assign payment allocations to Bills"
      }
    },
    "/api/BillPayment/{id}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ],
        "tags": [
          "BillPayment"
        ],
        "operationId": "BillPayment_GetByID",
        "summary": "Gets a Bill Payment by Payment Transaction ID",
        "description": "Gets a Bill Payment by Payment Transaction ID"
      }
    },
    "/api/Company": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_contacts"
            ]
          }
        ],
        "tags": [
          "Company"
        ],
        "operationId": "Company_Get",
        "summary": "Gets list of Companies",
        "description": "Gets list of Companies"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "write_contacts"
            ]
          }
        ],
        "tags": [
          "Company"
        ],
        "operationId": "Company_Post",
        "summary": "Create a Company",
        "description": "Create a Company"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "write_contacts"
            ]
          }
        ],
        "tags": [
          "Company"
        ],
        "description": "Requires CompanyID and a list of field names to update. The FieldsToUpdate field accepts a string array containing field names that should be updated.",
        "operationId": "Company_Put",
        "summary": "Update a Company record."
      }
    },
    "/api/Company/Lookup": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_contacts"
            ]
          }
        ],
        "tags": [
          "Company"
        ],
        "description": "Certain roles see a restricted set of companies based on their project memberships",
        "operationId": "CompanyLookup",
        "summary": "Gets minimal list of Companies."
      }
    },
    "/api/Company/{id}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_contacts"
            ]
          }
        ],
        "tags": [
          "Company"
        ],
        "operationId": "Company_GetByID",
        "summary": "Gets Company by Company ID",
        "description": "Gets Company by Company ID"
      }
    },
    "/api/Contact": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_contacts"
            ]
          }
        ],
        "tags": [
          "Contact"
        ],
        "operationId": "Contact_Get",
        "summary": "Gets list of Contacts",
        "description": "Gets list of Contacts"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "write_contacts"
            ]
          }
        ],
        "tags": [
          "Contact"
        ],
        "operationId": "Contact_Post",
        "summary": "Create a Contact",
        "description": "Create a Contact"
      }
    },
    "/api/Contact/{id}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_contacts"
            ]
          }
        ],
        "tags": [
          "Contact"
        ],
        "operationId": "Contact_GetByID",
        "summary": "Gets Contact by Contact ID",
        "description": "Gets Contact by Contact ID"
      }
    },
    "/api/CreditNote": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ],
        "tags": [
          "CreditNote"
        ],
        "operationId": "CreditNote_Get",
        "summary": "Gets list of CreditNotes",
        "description": "Gets list of CreditNotes"
      }
    },
    "/api/CreditNote/{id}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ],
        "tags": [
          "CreditNote"
        ],
        "operationId": "CreditNote_GetByID",
        "summary": "Gets Credit Note by CreditNoteID",
        "description": "Gets Credit Note by CreditNoteID"
      }
    },
    "/api/Currency": {
      "get": {
        "tags": [
          "Currency"
        ],
        "operationId": "Currency_Get",
        "summary": "Gets list of Currencies",
        "description": "Gets list of Currencies"
      }
    },
    "/api/Estimate": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ],
        "tags": [
          "Estimate"
        ],
        "description": "EstimateStatusCode values are: \"Draft\", \"Sent\", \"Accepted\", \"Converted\", \"Expired\", \"Rejected\"",
        "operationId": "Estimate_Get",
        "summary": "Gets list of Estimates"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "write_financials"
            ]
          }
        ],
        "tags": [
          "Estimate"
        ],
        "operationId": "Estimate_Post",
        "summary": "Create a new draft Estimate",
        "description": "Create a new draft Estimate"
      }
    },
    "/api/Estimate/{id}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ],
        "tags": [
          "Estimate"
        ],
        "operationId": "Estimate_GetByID",
        "summary": "Gets Estimate by Estimate ID",
        "description": "Gets Estimate by Estimate ID"
      }
    },
    "/api/Expense": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "write_expenses"
            ]
          }
        ],
        "tags": [
          "Expense"
        ],
        "operationId": "Expense_Delete",
        "summary": "Delete Expense Entries",
        "description": "Delete Expense Entries"
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "read_expenses"
            ]
          }
        ],
        "tags": [
          "Expense"
        ],
        "operationId": "Expense_Get",
        "summary": "Gets list of Expenses",
        "description": "Gets list of Expenses"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "write_expenses"
            ]
          }
        ],
        "tags": [
          "Expense"
        ],
        "description": "Create an Expense",
        "operationId": "Expense_Post",
        "summary": "Create an Expense"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "write_expenses"
            ]
          }
        ],
        "tags": [
          "Expense"
        ],
        "description": "Update an Expense",
        "operationId": "Expense_Put",
        "summary": "Update an Expense"
      }
    },
    "/api/Expense/Attachment": {
      "post": {
        "security": [
          {
            "oauth2": [
              "write_expenses"
            ]
          }
        ],
        "tags": [
          "Expense"
        ],
        "operationId": "ExpenseAttachment",
        "description": "POST /api/Expense/Attachment"
      }
    },
    "/api/Expense/{id}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_expenses"
            ]
          }
        ],
        "tags": [
          "Expense"
        ],
        "operationId": "Expense_GetByID",
        "summary": "Gets an Expense Entry by Expense ID",
        "description": "Gets an Expense Entry by Expense ID"
      }
    },
    "/api/ExpenseApproval/Submit": {
      "post": {
        "security": [
          {
            "oauth2": [
              "write_expenses"
            ]
          }
        ],
        "tags": [
          "Expense"
        ],
        "operationId": "ExpenseApproval",
        "summary": "Submit Expenses for Approval.",
        "description": "Submit Expenses for Approval."
      }
    },
    "/api/ExpenseCategory": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_expenses"
            ]
          }
        ],
        "tags": [
          "ExpenseCategory"
        ],
        "description": "The default sort order is by Name asc",
        "operationId": "ExpenseCategory_Get",
        "summary": "Gets list of Expense Categories"
      }
    },
    "/api/ExpenseGroup/Lookup": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_expenses"
            ]
          }
        ],
        "tags": [
          "ExpenseGroup"
        ],
        "description": "Expense Groups are for adhoc grouping of reported expenses. e.g. for expenses incurred on a Trip",
        "operationId": "ExpenseGroupLookup",
        "summary": "Gets minimal list of Expense Groups."
      }
    },
    "/api/ExpenseMerchant/Lookup": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_expenses"
            ]
          }
        ],
        "tags": [
          "ExpenseMerchant"
        ],
        "operationId": "ExpenseMerchangeLookup",
        "summary": "Gets minimal list of Expense Merchants.",
        "description": "Gets minimal list of Expense Merchants."
      }
    },
    "/api/ExpensePaymentMethod/Lookup": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_expenses"
            ]
          }
        ],
        "tags": [
          "ExpensePaymentMethod"
        ],
        "operationId": "ExpensePaymentMethodLookup",
        "summary": "Gets minimal list of Expense Payment Methods.",
        "description": "Gets minimal list of Expense Payment Methods."
      }
    },
    "/api/ExpenseSummary": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_expenses"
            ]
          }
        ],
        "tags": [
          "ExpenseSummary"
        ],
        "operationId": "ExpenseSummary_Get",
        "summary": "Gets Basic Summary of Expense Statistics",
        "description": "Gets Basic Summary of Expense Statistics"
      }
    },
    "/api/FixedAmount": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ],
        "tags": [
          "FixedAmount"
        ],
        "operationId": "FixedAmount_Get",
        "summary": "Gets list of Fixed Amounts",
        "description": "Gets list of Fixed Amounts"
      }
    },
    "/api/Inventory": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ],
        "tags": [
          "Inventory"
        ],
        "description": "Gets list of Inventory",
        "operationId": "Inventory_Get",
        "summary": "Gets list of Inventory"
      }
    },
    "/api/Inventory/{id}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ],
        "tags": [
          "Inventory"
        ],
        "operationId": "Inventory_GetByID",
        "summary": "Gets InventoryItem by InventoryItem ID",
        "description": "Gets InventoryItem by InventoryItem ID"
      }
    },
    "/api/Invoice": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ],
        "tags": [
          "Invoice"
        ],
        "description": "TransactionStatusCode values are: \"Draft\", \"Sent\", \"Late\", \"Paid\", \"Partial\", \"Void\"",
        "operationId": "Invoice_Get",
        "summary": "Gets list of Invoices"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "write_financials"
            ]
          }
        ],
        "tags": [
          "Invoice"
        ],
        "operationId": "Invoice_Post",
        "summary": "Create a new draft invoice",
        "description": "Create a new draft invoice"
      }
    },
    "/api/Invoice/{id}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ],
        "tags": [
          "Invoice"
        ],
        "operationId": "Invoice_GetByID",
        "summary": "Gets Invoice by Invoice ID",
        "description": "Gets Invoice by Invoice ID"
      }
    },
    "/api/Payment": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ],
        "tags": [
          "Payment"
        ],
        "operationId": "Payment_Get",
        "summary": "Gets list of Payments",
        "description": "Gets list of Payments"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "write_financials"
            ]
          }
        ],
        "tags": [
          "Payment"
        ],
        "operationId": "Payment_Post",
        "summary": "Create new Payment and optionally assign payment allocations to Invoices",
        "description": "Create new Payment and optionally assign payment allocations to Invoices"
      }
    },
    "/api/Payment/{id}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ],
        "tags": [
          "Payment"
        ],
        "operationId": "Payment_GetByID",
        "summary": "Gets Payment by Payment Transaction ID",
        "description": "Gets Payment by Payment Transaction ID"
      }
    },
    "/api/Project": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_projects"
            ]
          }
        ],
        "tags": [
          "Project"
        ],
        "operationId": "Project_Get",
        "summary": "Gets list of Projects",
        "description": "Gets list of Projects"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "write_projects"
            ]
          }
        ],
        "tags": [
          "Project"
        ],
        "operationId": "Project_Post",
        "summary": "Create a Project",
        "description": "Create a Project"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "write_projects"
            ]
          }
        ],
        "tags": [
          "Project"
        ],
        "description": "Update a Project",
        "operationId": "Project_Put",
        "summary": "Update an Project"
      }
    },
    "/api/Project/Lookup": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_projects"
            ]
          }
        ],
        "tags": [
          "Project"
        ],
        "operationId": "ProjectLookup",
        "summary": "Gets minimal list of active Projects for the current user",
        "description": "Gets minimal list of active Projects for the current user"
      }
    },
    "/api/Project/{id}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_projects"
            ]
          }
        ],
        "tags": [
          "Project"
        ],
        "operationId": "Project_GetByID",
        "summary": "Gets Project by Project ID",
        "description": "Gets Project by Project ID"
      }
    },
    "/api/ProjectMember": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_projects"
            ]
          }
        ],
        "tags": [
          "ProjectMember"
        ],
        "description": "Include at least one of ProjectID or UserID parameters.",
        "operationId": "ProjectMember_Get",
        "summary": "Gets list of Project Members"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "write_projects"
            ]
          }
        ],
        "tags": [
          "ProjectMember"
        ],
        "description": "the Amount columns for Cost, Budget, Rates should be specified as a decimal. Financial amounts assume the currency of the Customer company. Budget units depend on the Budget method set on the Project.",
        "operationId": "ProjectMember_Post",
        "summary": "Assign a user as a Member of a Project"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "write_projects"
            ]
          }
        ],
        "tags": [
          "ProjectMember"
        ],
        "description": "Fields are only updated if their field name is in the FieldsToUpdate string collection. The Amount columns for Cost, Budget, Rates if specified should be a decimal. Financial amounts assume the currency of the parent Company. Budget units depend on the Budget method set on the Project.",
        "operationId": "ProjectMember_Put",
        "summary": "Update a Member of a Project"
      }
    },
    "/api/ProjectTimesheetCategory": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_timesheets"
            ]
          }
        ],
        "tags": [
          "ProjectTimesheetCategory"
        ],
        "description": "The default sort order is by isBillable desc, Name asc",
        "operationId": "ProjectTimesheetCategory_Get",
        "summary": "Gets list of Project Timesheet Categories"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "write_projects"
            ]
          }
        ],
        "tags": [
          "ProjectTimesheetCategory"
        ],
        "description": "Assign a TimeSheetCategory to a Project.",
        "operationId": "ProjectTimesheetCategory_Post",
        "summary": "Assign a TimeSheetCategory to a Project."
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "write_projects"
            ]
          }
        ],
        "tags": [
          "ProjectTimesheetCategory"
        ],
        "description": "Update a TimeSheetCategory on a Project.",
        "operationId": "ProjectTimesheetCategory_Put",
        "summary": "Update a TimeSheetCategory on a Project."
      }
    },
    "/api/ScheduleAssignment": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_schedule"
            ]
          }
        ],
        "tags": [
          "ScheduleAssignment"
        ],
        "description": "Schedule assignments are per-day, and link to a parent Schedule Series.",
        "operationId": "ScheduleAssignment_Get",
        "summary": "Gets list of Schedule Assignments."
      }
    },
    "/api/ScheduleSeries": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_schedule"
            ]
          }
        ],
        "tags": [
          "ScheduleSeries"
        ],
        "description": "Schedule Series represents a strip of time assigned to a user over a date range, for a certain number of hours per day. They can be for Leave or for project work Bookings.",
        "operationId": "ScheduleSeries_Get",
        "summary": "Gets list of Schedule Series"
      }
    },
    "/api/Section": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "write_projects"
            ]
          }
        ],
        "tags": [
          "Section"
        ],
        "operationId": "Section_Delete",
        "summary": "Delete a Section",
        "description": "Delete a Section"
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "read_projects"
            ]
          }
        ],
        "tags": [
          "Section"
        ],
        "operationId": "Section_Get",
        "summary": "Gets list of Sections",
        "description": "Gets list of Sections"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "write_projects"
            ]
          }
        ],
        "tags": [
          "Section"
        ],
        "operationId": "Section_Post",
        "summary": "Create a Section",
        "description": "Create a Section"
      }
    },
    "/api/Task": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "write_projects"
            ]
          }
        ],
        "tags": [
          "Task"
        ],
        "operationId": "Task_Delete",
        "summary": "Delete a Task",
        "description": "Delete a Task"
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "read_projects"
            ]
          }
        ],
        "tags": [
          "Task"
        ],
        "operationId": "Task_Get",
        "summary": "Gets list of Tasks",
        "description": "Gets list of Tasks"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "write_projects"
            ]
          }
        ],
        "tags": [
          "Task"
        ],
        "operationId": "Task_Post",
        "summary": "Create a Task",
        "description": "Create a Task"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "write_projects"
            ]
          }
        ],
        "tags": [
          "Task"
        ],
        "description": "Requires TaskID and a list of field names to update. The FieldsToUpdate field accepts a string array containing field names that should be updated.",
        "operationId": "Task_Put",
        "summary": "Update a Task."
      }
    },
    "/api/Task/Lookup": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_projects"
            ]
          }
        ],
        "tags": [
          "Task"
        ],
        "description": "Groups Tasks by Section. Default sort is by Section Title followed by Task Title",
        "operationId": "TaskLookup",
        "summary": "Gets minimal list of Tasks for the current user"
      }
    },
    "/api/Task/{id}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_projects"
            ]
          }
        ],
        "tags": [
          "Task"
        ],
        "operationId": "Task_GetByID",
        "summary": "Gets Task by Task ID",
        "description": "Gets Task by Task ID"
      }
    },
    "/api/TaskStatus": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_projects"
            ]
          }
        ],
        "tags": [
          "TaskStatus"
        ],
        "operationId": "TaskStatus_Get",
        "summary": "Gets list of Task Statuses",
        "description": "Gets list of Task Statuses"
      }
    },
    "/api/TaskType": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_projects"
            ]
          }
        ],
        "tags": [
          "TaskType"
        ],
        "operationId": "TaskType_Get",
        "summary": "Gets list of Task Types",
        "description": "Gets list of Task Types"
      }
    },
    "/api/Tax": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_financials"
            ]
          }
        ],
        "tags": [
          "Tax"
        ],
        "operationId": "Tax_Get",
        "summary": "Get List of Taxes configured in the Avaza account.",
        "description": "Get List of Taxes configured in the Avaza account."
      }
    },
    "/api/Timesheet": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_timesheets"
            ]
          }
        ],
        "tags": [
          "Timesheet"
        ],
        "operationId": "Timesheet_Get",
        "summary": "Gets list of Timsheets",
        "description": "Gets list of Timsheets"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "write_timesheets"
            ]
          }
        ],
        "tags": [
          "Timesheet"
        ],
        "operationId": "Timesheet_Post",
        "summary": "Create a new Timesheet Entry",
        "description": "Create a new Timesheet Entry"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "write_timesheets"
            ]
          }
        ],
        "tags": [
          "Timesheet"
        ],
        "description": "The FieldsToUpdate field expects a string array collection of the field names you would like updated. Valid fields to update inlcude \"ProjectIDFK\", \"TimeSheetCategoryIDFK\", \"TaskIDFK\", \"Duration\", \"EntryDate\", \"Notes\", \"hasStartEndTime\", \"CustomMetadata\". If you intend to provide start/end times on timesheets, this is achieved by including the start time in the EntryDate field (Iso date format), along with a Duration (decimal format).",
        "operationId": "Timesheet_Put",
        "summary": "Update a Timesheet"
      }
    },
    "/api/Timesheet/{id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "write_timesheets"
            ]
          }
        ],
        "tags": [
          "Timesheet"
        ],
        "operationId": "Timesheet_Delete",
        "summary": "Delete a Timesheet Entry",
        "description": "Delete a Timesheet Entry"
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "read_timesheets"
            ]
          }
        ],
        "tags": [
          "Timesheet"
        ],
        "operationId": "Timesheet_GetByID",
        "summary": "Gets a Timesheet Entry by Timesheet ID",
        "description": "Gets a Timesheet Entry by Timesheet ID"
      }
    },
    "/api/TimesheetSubmission": {
      "post": {
        "security": [
          {
            "oauth2": [
              "write_timesheets"
            ]
          }
        ],
        "tags": [
          "TimesheetSubmission"
        ],
        "description": "Either provide a a specific Day (WholeDayOf) or any day in a Week (WholeWeekOf) to submit all draft timesheets in that day or week",
        "operationId": "TimesheetSubmission_Post",
        "summary": "Submit Timesheets for Approval."
      }
    },
    "/api/TimesheetSummary": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_timesheets"
            ]
          }
        ],
        "tags": [
          "TimesheetSummary"
        ],
        "operationId": "TimesheetSummary_Get",
        "summary": "Gets Basic Summary of Timesheet Statistics",
        "description": "Gets Basic Summary of Timesheet Statistics"
      }
    },
    "/api/TimesheetTimer": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_timesheets"
            ]
          }
        ],
        "tags": [
          "TimesheetTimer"
        ],
        "operationId": "TimesheetTimer_GetRunningTimer",
        "summary": "Gets the  Running Timer if there is one for a user.",
        "description": "Gets the  Running Timer if there is one for a user."
      }
    },
    "/api/TimesheetTimer/{id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "write_timesheets"
            ]
          }
        ],
        "tags": [
          "TimesheetTimer"
        ],
        "operationId": "TimesheetTimer_StopTimer",
        "summary": "Stop the timer running on an existing Timesheet Entry",
        "description": "Stop the timer running on an existing Timesheet Entry"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "write_timesheets"
            ]
          }
        ],
        "tags": [
          "TimesheetTimer"
        ],
        "operationId": "TimesheetTimer_StartTimer",
        "summary": "Starts a Timer running on an existing Timesheet Entry",
        "description": "Starts a Timer running on an existing Timesheet Entry"
      }
    },
    "/api/UserProfile": {
      "get": {
        "security": [
          {
            "oauth2": [
              "read_users"
            ]
          }
        ],
        "tags": [
          "UserProfile"
        ],
        "description": "Admin and Finance Managers can see all. Other users are limited to seeing their own profile.",
        "operationId": "UserProfile_Get",
        "summary": "Get Collection of Users who have roles in the current Avaza account."
      }
    },
    "/api/Webhook": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "webhook_notifications"
            ]
          }
        ],
        "tags": [
          "Webhook"
        ],
        "operationId": "Webhook_DeleteByUrl",
        "summary": "Delete webhook subscription by URL",
        "description": "Delete webhook subscription by URL"
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "webhook_notifications"
            ]
          }
        ],
        "tags": [
          "Webhook"
        ],
        "operationId": "Webhook_Get",
        "summary": "Get list of Webhook Subscriptions",
        "description": "Get list of Webhook Subscriptions"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "webhook_notifications",
              "read_contacts",
              "read_account",
              "read_users",
              "read_financials",
              "read_projects",
              "read_schedule",
              "read_timesheets",
              "read_expenses",
              "write_contacts",
              "write_account",
              "write_users",
              "write_financials",
              "write_projects",
              "write_schedule",
              "write_timesheets",
              "write_expenses"
            ]
          }
        ],
        "tags": [
          "Webhook"
        ],
        "description": "When you receive a webhook, you should respond with Http 200 OK Status Code, otherwise we will retry. To create a webhook, you need both the webhook_notifications scope, as well as the scope for the required entity being monitored.  Event values are: \"company_created\", \"company_deleted\", \"company_updated\", \"contact_created\", \"contact_deleted\", \"contact_updated\", \"invoice_created\", \"invoice_sent\",\"invoice_updated\",\"invoice_deleted\", \"project_created\",[...]",
        "operationId": "Webhook_Post",
        "summary": "Subscribe to Webhook. On success, returns ID of webhook subscription."
      }
    },
    "/api/Webhook/{id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "webhook_notifications"
            ]
          }
        ],
        "tags": [
          "Webhook"
        ],
        "operationId": "Webhook_Delete",
        "summary": "Delete Webhook Subscription by ID",
        "description": "Delete Webhook Subscription by ID"
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "webhook_notifications"
            ]
          }
        ],
        "tags": [
          "Webhook"
        ],
        "operationId": "Webhook_GetByID",
        "summary": "Get Webhook Subscription by SubscriptionID",
        "description": "Get Webhook Subscription by SubscriptionID"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "description": "OAuth2 Implicit Grant",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://any.avaza.com/oauth2/authorize",
            "scopes": {
              "read_account": "Read access to Account metadata",
              "read_contacts": "Read access to Customers, Contacts",
              "read_expenses": "Read access to Expense Details",
              "read_financials": "Read access to Estimates, Invoices, Payments, Credit Notes",
              "read_projects": "Read access to Projects, Project Settings, Tasks",
              "read_schedule": "Read access to Schedule Details",
              "read_timesheets": "Read access to Timesheet Details",
              "read_users": "Read access to User Profiles",
              "webhook_notifications": "Read access to webhook notification events",
              "write_account": "Write access to Account metadata",
              "write_contacts": "Write access to Customers, Contacts",
              "write_expenses": "Write access to Expense module",
              "write_financials": "Write access to Estimates, Invoices, Payments, Credit Notes",
              "write_projects": "Write access to Projects, Project Settings, Tasks",
              "write_schedule": "Write access to Schedule module",
              "write_timesheets": "Write access to Timesheets module",
              "write_users": "Write access to User Profiles"
            }
          }
        },
        "type": "oauth2"
      }
    }
  },
  "tags": [
    {
      "name": "Account"
    },
    {
      "name": "Bill"
    },
    {
      "name": "BillPayment"
    },
    {
      "name": "Company"
    },
    {
      "name": "Contact"
    },
    {
      "name": "CreditNote"
    },
    {
      "name": "Currency"
    },
    {
      "name": "Estimate"
    },
    {
      "name": "Expense"
    },
    {
      "name": "ExpenseCategory"
    },
    {
      "name": "ExpenseGroup"
    },
    {
      "name": "ExpenseMerchant"
    },
    {
      "name": "ExpensePaymentMethod"
    },
    {
      "name": "ExpenseSummary"
    },
    {
      "name": "FixedAmount"
    },
    {
      "name": "Inventory"
    },
    {
      "name": "Invoice"
    },
    {
      "name": "Payment"
    },
    {
      "name": "Project"
    },
    {
      "name": "ProjectMember"
    },
    {
      "name": "ProjectTimesheetCategory"
    },
    {
      "name": "ScheduleAssignment"
    },
    {
      "name": "ScheduleSeries"
    },
    {
      "name": "Section"
    },
    {
      "name": "Task"
    },
    {
      "name": "TaskStatus"
    },
    {
      "name": "TaskType"
    },
    {
      "name": "Tax"
    },
    {
      "name": "Timesheet"
    },
    {
      "name": "TimesheetSubmission"
    },
    {
      "name": "TimesheetSummary"
    },
    {
      "name": "TimesheetTimer"
    },
    {
      "name": "UserProfile"
    },
    {
      "name": "Webhook"
    }
  ]
}
