{
  "openapi": "3.0.0",
  "info": {
    "title": "Zoho Expense API",
    "version": "v1",
    "contact": {
      "name": "API Support"
    },
    "description": "Zoho Expense API - OpenAPI Specification"
  },
  "servers": [
    {
      "url": "https://www.zohoapis.com/expense/v1"
    }
  ],
  "paths": {
    "/settings/currencies": {
      "post": {
        "tags": [
          "currencies"
        ],
        "operationId": "create_currency",
        "summary": "Create a currency",
        "description": "Create a currency.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.currency.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "currencies"
        ],
        "operationId": "list_currencies",
        "summary": "Retrieve list of currencies",
        "description": "Details of all existing currencies.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.currency.READ"
            ]
          }
        ]
      }
    },
    "/settings/currencies/{currency_id}": {
      "get": {
        "tags": [
          "currencies"
        ],
        "operationId": "get_currency",
        "summary": "Retrieve details of a currency",
        "description": "Details of an existing currency.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.expense.READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "currencies"
        ],
        "operationId": "update_currency",
        "summary": "Update details of a currency",
        "description": "Update the details of an existing currency.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.currency.UPDATE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "currencies"
        ],
        "operationId": "delete_currency",
        "summary": "Delete a currency",
        "description": "Delete an existing currency.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.currency.DELETE"
            ]
          }
        ]
      }
    },
    "/contacts": {
      "post": {
        "tags": [
          "customers"
        ],
        "operationId": "create_customer",
        "summary": "Create a customer",
        "description": "Create a new customer.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.contacts.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "customers"
        ],
        "operationId": "list_customers",
        "summary": "List of all customers",
        "description": "List of all customers.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.customer.READ"
            ]
          }
        ]
      }
    },
    "/contacts/{customer_id}": {
      "get": {
        "tags": [
          "customers"
        ],
        "operationId": "get_customer",
        "summary": "Retrieve details of a customer",
        "description": "Details of an existing customer.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.customer.READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "customers"
        ],
        "operationId": "update_customer",
        "summary": "Update a customer",
        "description": "Update the details of an existing customer.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.customer.UPDATE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "customers"
        ],
        "operationId": "delete_customer",
        "summary": "Delete a customer",
        "description": "Delete an existing customer.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.contacts.DELETE"
            ]
          }
        ]
      }
    },
    "/expensecategories": {
      "post": {
        "tags": [
          "expense-categories"
        ],
        "operationId": "create_expense_category",
        "summary": "Create an expense category",
        "description": "Create a new expense category.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.expensecategory.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "expense-categories"
        ],
        "operationId": "list_expense_categories",
        "summary": "List of expense categories",
        "description": "List of all active expense categories.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.expensecategory.READ"
            ]
          }
        ]
      }
    },
    "/expensecategories/{expense_category_id}": {
      "get": {
        "tags": [
          "expense-categories"
        ],
        "operationId": "get_expense_category",
        "summary": "Retrieve details of an expense category",
        "description": "Details of an existing expense category.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.expensecategory.READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "expense-categories"
        ],
        "operationId": "update_expense_category",
        "summary": "Update an expense category",
        "description": "Update the details of an existing expense category.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.expensecategory.UPDATE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "expense-categories"
        ],
        "operationId": "delete_expense_category",
        "summary": "Delete an expense category",
        "description": "Delete an existing expense category.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.expensecategory.DELETE"
            ]
          }
        ]
      }
    },
    "/expensecategories/{expense_category_id}/show": {
      "post": {
        "tags": [
          "expense-categories"
        ],
        "operationId": "enable_expense_category",
        "summary": "Enable an expense category",
        "description": "Enable an expense category.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.expensecategory.CREATE"
            ]
          }
        ]
      }
    },
    "/expensecategories/{expense_category_id}/hide": {
      "post": {
        "tags": [
          "expense-categories"
        ],
        "operationId": "disable_expense_category",
        "summary": "Disable an expense category",
        "description": "Disable an expense category.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.expensecategory.CREATE"
            ]
          }
        ]
      }
    },
    "/expensereports": {
      "post": {
        "tags": [
          "expense-reports"
        ],
        "operationId": "create_expense_report",
        "summary": "Create an expense report",
        "description": "Create a new expense report.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.expensereport.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "expense-reports"
        ],
        "operationId": "list_expense_reports",
        "summary": "List of all expense reports",
        "description": "List of all the submitted expense reports.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.expensereport.READ"
            ]
          }
        ]
      }
    },
    "/expensereports/{expense_report_id}": {
      "get": {
        "tags": [
          "expense-reports"
        ],
        "operationId": "get_expense_report",
        "summary": "Retrieve details of an expense report",
        "description": "Details of an existing expense report.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.expensereport.READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "expense-reports"
        ],
        "operationId": "update_expense_report",
        "summary": "Update an expense report",
        "description": "Update the details of an expense report.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.expensereport.UPDATE"
            ]
          }
        ]
      }
    },
    "/expensereports/{expense_report_id}/approve": {
      "post": {
        "tags": [
          "expense-reports"
        ],
        "operationId": "approve_expense_report",
        "summary": "Approve an expense report",
        "description": "Approve an expense report.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.approval.CREATE"
            ]
          }
        ]
      }
    },
    "/expensereports/{expense_report_id}/reject": {
      "post": {
        "tags": [
          "expense-reports"
        ],
        "operationId": "reject_expense_report",
        "summary": "Reject an expense report",
        "description": "Reject an expense report.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.approval.CREATE"
            ]
          }
        ]
      }
    },
    "/expensereports/{expense_report_id}/reimburse": {
      "post": {
        "tags": [
          "expense-reports"
        ],
        "operationId": "reimburse_expense_report",
        "summary": "Reimburse an expense report",
        "description": "Reimburse an expense report.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.reimbursement.CREATE"
            ]
          }
        ]
      }
    },
    "/expensereports/{expense_report_id}/approvalhistory": {
      "get": {
        "tags": [
          "expense-reports"
        ],
        "operationId": "approval_history_expense_report",
        "summary": "Approval history of an expense report",
        "description": "Approval history of an expense report.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.expensereport.READ"
            ]
          }
        ]
      }
    },
    "/expenses": {
      "post": {
        "tags": [
          "receipts"
        ],
        "operationId": "create_upload_receipts",
        "summary": "Upload Receipts",
        "description": "<p>Upload receipts for autoscanning.</p>",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.expense.CREATE"
            ]
          }
        ]
      }
    },
    "/reports/expensedetails": {
      "get": {
        "tags": [
          "expenses"
        ],
        "operationId": "list_expenses",
        "summary": "List all expenses",
        "description": "List of all existing expenses.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.expense.READ"
            ]
          }
        ]
      }
    },
    "/expenses/{expense_id}": {
      "put": {
        "tags": [
          "expenses"
        ],
        "operationId": "update_expense",
        "summary": "Update an expense",
        "description": "Update the details of an expense.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.expense.UPDATE"
            ]
          }
        ]
      }
    },
    "/expenses/{expense_id}/merge": {
      "post": {
        "tags": [
          "expenses"
        ],
        "operationId": "merge_expenses",
        "summary": "Merge expenses",
        "description": "Merge multiple expenses.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.expense.CREATE"
            ]
          }
        ]
      }
    },
    "/organizations": {
      "post": {
        "tags": [
          "organizations"
        ],
        "operationId": "create_organization",
        "summary": "Create an organization",
        "description": "Create an organization.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.orgsettings.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "organizations"
        ],
        "operationId": "list_organizations",
        "summary": "List organizations",
        "description": "Get the list of organizations.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.orgsettings.READ"
            ]
          }
        ]
      }
    },
    "/organizations/{organization_id}": {
      "put": {
        "tags": [
          "organizations"
        ],
        "operationId": "update_organization",
        "summary": "Update an organization",
        "description": "Update the details of an organization.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.orgsettings.UPDATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "organizations"
        ],
        "operationId": "get_organization",
        "summary": "Get an organization",
        "description": "Get the details of an organization.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.orgsettings.READ"
            ]
          }
        ]
      }
    },
    "/projects": {
      "post": {
        "tags": [
          "projects"
        ],
        "operationId": "create_project",
        "summary": "Create a project",
        "description": "Create a new project.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.project.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "projects"
        ],
        "operationId": "list_projects",
        "summary": "List of all projects",
        "description": "List of all projects.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.project.READ"
            ]
          }
        ]
      }
    },
    "/projects/{project_id}": {
      "get": {
        "tags": [
          "projects"
        ],
        "operationId": "get_project",
        "summary": "Retrieve details of a project",
        "description": "Details of an existing project.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.project.READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "projects"
        ],
        "operationId": "update_project",
        "summary": "Update the details of a project",
        "description": "Update the details of an existing project.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.project.UPDATE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "projects"
        ],
        "operationId": "delete_project",
        "summary": "Delete a project",
        "description": "Delete an existing project.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.project.DELETE"
            ]
          }
        ]
      }
    },
    "/projects/{project_id}/active": {
      "post": {
        "tags": [
          "projects"
        ],
        "operationId": "activate_project",
        "summary": "Make a project active",
        "description": "Mark a project as active.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.project.CREATE"
            ]
          }
        ]
      }
    },
    "/projects/{project_id}/inactive": {
      "post": {
        "tags": [
          "projects"
        ],
        "operationId": "deactivate_project",
        "summary": "Make a project inactive",
        "description": "Mark a project as inactive.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.project.CREATE"
            ]
          }
        ]
      }
    },
    "/reportingtags": {
      "get": {
        "tags": [
          "reporting-tags"
        ],
        "operationId": "get_tags",
        "summary": "List of all Reporting Tags",
        "description": "Get a list of all reporting tags in the preferred order that you can set.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.settings.READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "reporting-tags"
        ],
        "operationId": "create_tag",
        "summary": "Create Reporting Tag",
        "description": "Create a reporting tag",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.settings.CREATE"
            ]
          }
        ]
      }
    },
    "/reportingtags/{tag_id}": {
      "post": {
        "tags": [
          "reporting-tags"
        ],
        "operationId": "mark_default_option",
        "summary": "Mark an option as default for a reporting tag",
        "description": "Mark an option as the default option or clear default option for a reporting tag.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.settings.READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "reporting-tags"
        ],
        "operationId": "update_tag",
        "summary": "Update Reporting Tag",
        "description": "Update a reporting tag",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.settings.UPDATE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "reporting-tags"
        ],
        "operationId": "delete_tag",
        "summary": "Delete a reporting tag",
        "description": "Delete a reporting tag. If there are any usages of the reporting tag in transactions,  custom views or workflows, you will not be able to delete the tag.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.settings.DELETE"
            ]
          }
        ]
      }
    },
    "/reportingtags/{tag_id}/options": {
      "put": {
        "tags": [
          "reporting-tags"
        ],
        "operationId": "update_tag_options",
        "summary": "Update Reporting Tag Options",
        "description": "Create, update or delete the options of a reporting tag. Reorder and arrange them in an hierarchical structure as per your organization requirements. <br><b>NOTE:</b> <br><ol> <li>An option cannot be a child option beyond five hierarchical level.</li> <li>The overall children of an option cannot exceed 500 options.</li></ol>",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.settings.UPDATE"
            ]
          }
        ]
      }
    },
    "/reportingtags/{tag_id}/criteria": {
      "put": {
        "tags": [
          "reporting-tags"
        ],
        "operationId": "update_tag_criteria",
        "summary": "Update Reporting Tag - Visibility Conditions",
        "description": "Update the visibility conditions (or filter in some places) of a reporting tag. You can set other tags or location as filters for a tag. Check our help document to know about the requirements of a tag to be associated as a filter to another tag.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.settings.UPDATE"
            ]
          }
        ]
      }
    },
    "/reportingtags/{tag_id}/active": {
      "post": {
        "tags": [
          "reporting-tags"
        ],
        "operationId": "active_tag",
        "summary": "Mark Reporting Tag as active",
        "description": "Mark a reporting tag as active so that you can use it on entities which you allowed.  A newly created tag will be in draft state. Use this to mark that tag as ready.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.settings.UPDATE"
            ]
          }
        ]
      }
    },
    "/reportingtags/{tag_id}/inactive": {
      "post": {
        "tags": [
          "reporting-tags"
        ],
        "operationId": "inactive_tag",
        "summary": "Mark Reporting Tag as inactive",
        "description": "Mark a reporting tag as inactive.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.settings.UPDATE"
            ]
          }
        ]
      }
    },
    "/reportingtags/{tag_id}/option/(\\d+)/active": {
      "post": {
        "tags": [
          "reporting-tags"
        ],
        "operationId": "active_tag_option",
        "summary": "Mark an option as active",
        "description": "Mark a reporting tag's option as active.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.settings.UPDATE"
            ]
          }
        ]
      }
    },
    "/reportingtags/{tag_id}/option/(\\d+)/inactive": {
      "post": {
        "tags": [
          "reporting-tags"
        ],
        "operationId": "inactive_tag_option",
        "summary": "Mark an option as inactive",
        "description": "Mark a reporting tag's option as inactive.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.settings.UPDATE"
            ]
          }
        ]
      }
    },
    "/reportingtags/options": {
      "get": {
        "tags": [
          "reporting-tags"
        ],
        "operationId": "get_all_tag_options",
        "summary": "Get Reporting Tags Options Detail Page",
        "description": "Get the options and its criteria details of a reporting tag. For each page, you can retrieve only 200 options.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.settings.READ"
            ]
          }
        ]
      }
    },
    "/reportingtags/(\\d+)/options/all": {
      "get": {
        "tags": [
          "reporting-tags"
        ],
        "operationId": "all_tag_options",
        "summary": "Get all Options",
        "description": "Get all options for a reporting tag.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.settings.READ"
            ]
          }
        ]
      }
    },
    "/reportingtags/reorder": {
      "put": {
        "tags": [
          "reporting-tags"
        ],
        "operationId": "reorder_tags",
        "summary": "Reorder Reporting Tags",
        "description": "Reorder the reporting tags in your organization. The order of tags will be followed in transactions and reports.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.settings.UPDATE"
            ]
          }
        ]
      }
    },
    "/settings/taxes": {
      "post": {
        "tags": [
          "taxes"
        ],
        "operationId": "create_tax",
        "summary": "Create a tax",
        "description": "Create a tax.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.tax.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "taxes"
        ],
        "operationId": "list_taxes",
        "summary": "Retrieve list of taxes",
        "description": "Details of all existing taxes.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.tax.READ"
            ]
          }
        ]
      }
    },
    "/settings/taxes/{tax_id}": {
      "get": {
        "tags": [
          "taxes"
        ],
        "operationId": "get_tax",
        "summary": "Retrieve details of a tax",
        "description": "Details of an existing tax.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.tax.READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "taxes"
        ],
        "operationId": "update_tax",
        "summary": "Update details of a tax",
        "description": "Update the details of an existing tax.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.tax.UPDATE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "taxes"
        ],
        "operationId": "delete_tax",
        "summary": "Delete a tax",
        "description": "Delete an existing tax.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.tax.DELETE"
            ]
          }
        ]
      }
    },
    "/settings/taxgroups/{tax_group_id}": {
      "get": {
        "tags": [
          "taxes"
        ],
        "operationId": "get_tax_group",
        "summary": "Retrieve details of a tax group",
        "description": "Details of an existing tax group.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.tax.READ"
            ]
          }
        ]
      }
    },
    "/trips": {
      "post": {
        "tags": [
          "trips"
        ],
        "operationId": "create_trip",
        "summary": "Create a trip",
        "description": "Create a new trip.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.trip.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "trips"
        ],
        "operationId": "list_trips",
        "summary": "Retrive list of all trips",
        "description": "List all existing trips.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.trip.READ"
            ]
          }
        ]
      }
    },
    "/trips/{trip_id}": {
      "get": {
        "tags": [
          "trips"
        ],
        "operationId": "get_trip",
        "summary": "Retrive details of a trip",
        "description": "Retrive details of an existing trip.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.trip.READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "trips"
        ],
        "operationId": "update_trip",
        "summary": "Update a trip",
        "description": "Update an existing Trip.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.trip.UPDATE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "trips"
        ],
        "operationId": "delete_trip",
        "summary": "Delete a trip request",
        "description": "Delete a trip request. Approved, Closed and Cancelled trips cannot be deleted.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.trip.DELETE"
            ]
          }
        ]
      }
    },
    "/trips/{trip_id}/approve": {
      "post": {
        "tags": [
          "trips"
        ],
        "operationId": "approve_trip",
        "summary": "Approve a trip request",
        "description": "Approve a submitted trip request.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.approval.CREATE"
            ]
          }
        ]
      }
    },
    "/trips/{trip_id}/reject": {
      "post": {
        "tags": [
          "trips"
        ],
        "operationId": "reject_trip",
        "summary": "Reject a trip request",
        "description": "Reject a submitted trip request.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.approval.CREATE"
            ]
          }
        ]
      }
    },
    "/trips/{trip_id}/cancel": {
      "post": {
        "tags": [
          "trips"
        ],
        "operationId": "cancel_trip",
        "summary": "Cancel a trip",
        "description": "Cancel a trip.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.trip.CREATE"
            ]
          }
        ]
      }
    },
    "/trips/{trip_id}/close": {
      "post": {
        "tags": [
          "trips"
        ],
        "operationId": "close_trip",
        "summary": "Close a trip",
        "description": "Close an approved trip.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.trip.CREATE"
            ]
          }
        ]
      }
    },
    "/users": {
      "post": {
        "tags": [
          "users"
        ],
        "operationId": "create_user",
        "summary": "Create an user",
        "description": "Create a new user.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.users.CREATE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "users"
        ],
        "operationId": "list_users",
        "summary": "Retrieve list of users",
        "description": "Details of all existing users.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.users.READ"
            ]
          }
        ]
      }
    },
    "/users/{user_id}": {
      "get": {
        "tags": [
          "users"
        ],
        "operationId": "get_user",
        "summary": "Retrieve details of an user",
        "description": "Details of an existing user.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.users.READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "users"
        ],
        "operationId": "update_user",
        "summary": "Update details of an user",
        "description": "Update the details of an existing user.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.users.UPDATE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "users"
        ],
        "operationId": "delete_user",
        "summary": "Delete an user",
        "description": "Delete an existing user.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.users.DELETE"
            ]
          }
        ]
      }
    },
    "/users/{user_id}/inactive": {
      "post": {
        "tags": [
          "users"
        ],
        "operationId": "deactivate_user",
        "summary": "Make an user inactive",
        "description": "Make an user inactive.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.users.CREATE"
            ]
          }
        ]
      }
    },
    "/users/{user_id}/active": {
      "post": {
        "tags": [
          "users"
        ],
        "operationId": "activate_user",
        "summary": "Make an user active",
        "description": "Make an user active.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.users.CREATE"
            ]
          }
        ]
      }
    },
    "/users/{user_id}/role/{role_id}": {
      "post": {
        "tags": [
          "users"
        ],
        "operationId": "assign_role_to_user",
        "summary": "Assign a role to user",
        "description": "Assign a role to user.",
        "deprecated": false,
        "security": [
          {
            "Zoho_Auth": [
              "ZohoExpense.users.CREATE"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Zoho_Auth": {
        "type": "oauth2",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://accounts.zoho.com/oauth/v2/auth",
            "scopes": {
              "ZohoExpense.users.CREATE": "Create user",
              "ZohoExpense.users.READ": "Read user",
              "ZohoExpense.users.UPDATE": "Update user",
              "ZohoExpense.users.DELETE": "Delete user"
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "currencies"
    },
    {
      "name": "customers"
    },
    {
      "name": "expense-categories"
    },
    {
      "name": "expense-reports"
    },
    {
      "name": "expenses"
    },
    {
      "name": "organizations"
    },
    {
      "name": "projects"
    },
    {
      "name": "receipts"
    },
    {
      "name": "reporting-tags"
    },
    {
      "name": "taxes"
    },
    {
      "name": "trips"
    },
    {
      "name": "users"
    }
  ]
}
