{
  "openapi": "3.1.0",
  "info": {
    "title": "YouTube Data API",
    "version": "3.0",
    "description": "The YouTube Data API v3 lets you incorporate YouTube functionality into your application. You can use the API to search for videos, retrieve channel and playlist information, manage subscriptions, and more.",
    "contact": {
      "name": "Google",
      "url": "https://developers.google.com/youtube/v3"
    },
    "x-apisguru-categories": [
      "media"
    ],
    "x-logo": {
      "url": "https://www.youtube.com/s/desktop/favicon.ico"
    }
  },
  "servers": [
    {
      "url": "https://www.googleapis.com/youtube/v3"
    }
  ],
  "security": [
    {
      "apiKey": []
    }
  ],
  "components": {
    "securitySchemes": {
      "apiKey": {
        "type": "apiKey",
        "in": "query",
        "name": "key",
        "description": "YouTube Data API key."
      },
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
            "tokenUrl": "https://oauth2.googleapis.com/token",
            "scopes": {
              "https://www.googleapis.com/auth/youtube": "Manage your YouTube account",
              "https://www.googleapis.com/auth/youtube.readonly": "View your YouTube account",
              "https://www.googleapis.com/auth/youtube.force-ssl": "See, edit, and permanently delete your YouTube videos, ratings, comments and captions",
              "https://www.googleapis.com/auth/youtube.upload": "Manage your YouTube videos"
            }
          }
        }
      }
    }
  },
  "paths": {
    "/search": {
      "get": {
        "operationId": "searchList",
        "summary": "Search for videos, channels, and playlists",
        "tags": [
          "Search"
        ],
        "description": "Search for videos, channels, and playlists"
      }
    },
    "/videos": {
      "get": {
        "operationId": "videosList",
        "summary": "List videos",
        "tags": [
          "Videos"
        ],
        "description": "List videos"
      }
    },
    "/videos/rate": {
      "post": {
        "operationId": "videosRate",
        "summary": "Rate a video (like/dislike)",
        "tags": [
          "Videos"
        ],
        "security": [
          {
            "oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ]
          }
        ],
        "description": "Rate a video (like/dislike)"
      }
    },
    "/channels": {
      "get": {
        "operationId": "channelsList",
        "summary": "List channels",
        "tags": [
          "Channels"
        ],
        "description": "List channels"
      }
    },
    "/playlists": {
      "get": {
        "operationId": "playlistsList",
        "summary": "List playlists",
        "tags": [
          "Playlists"
        ],
        "description": "List playlists"
      },
      "post": {
        "operationId": "playlistsInsert",
        "summary": "Create a playlist",
        "tags": [
          "Playlists"
        ],
        "security": [
          {
            "oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ]
          }
        ],
        "description": "Create a playlist"
      },
      "put": {
        "operationId": "playlistsUpdate",
        "summary": "Update a playlist",
        "tags": [
          "Playlists"
        ],
        "security": [
          {
            "oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ]
          }
        ],
        "description": "Update a playlist"
      },
      "delete": {
        "operationId": "playlistsDelete",
        "summary": "Delete a playlist",
        "tags": [
          "Playlists"
        ],
        "security": [
          {
            "oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ]
          }
        ],
        "description": "Delete a playlist"
      }
    },
    "/playlistItems": {
      "get": {
        "operationId": "playlistItemsList",
        "summary": "List playlist items",
        "tags": [
          "Playlists"
        ],
        "description": "List playlist items"
      },
      "post": {
        "operationId": "playlistItemsInsert",
        "summary": "Add an item to a playlist",
        "tags": [
          "Playlists"
        ],
        "security": [
          {
            "oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ]
          }
        ],
        "description": "Add an item to a playlist"
      },
      "delete": {
        "operationId": "playlistItemsDelete",
        "summary": "Delete a playlist item",
        "tags": [
          "Playlists"
        ],
        "security": [
          {
            "oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ]
          }
        ],
        "description": "Delete a playlist item"
      }
    },
    "/commentThreads": {
      "get": {
        "operationId": "commentThreadsList",
        "summary": "List comment threads",
        "tags": [
          "Comments"
        ],
        "description": "List comment threads"
      },
      "post": {
        "operationId": "commentThreadsInsert",
        "summary": "Create a comment thread",
        "tags": [
          "Comments"
        ],
        "security": [
          {
            "oauth2": [
              "https://www.googleapis.com/auth/youtube.force-ssl"
            ]
          }
        ],
        "description": "Create a comment thread"
      }
    },
    "/subscriptions": {
      "get": {
        "operationId": "subscriptionsList",
        "summary": "List subscriptions",
        "tags": [
          "Subscriptions"
        ],
        "security": [
          {
            "oauth2": [
              "https://www.googleapis.com/auth/youtube.readonly"
            ]
          }
        ],
        "description": "List subscriptions"
      },
      "post": {
        "operationId": "subscriptionsInsert",
        "summary": "Subscribe to a channel",
        "tags": [
          "Subscriptions"
        ],
        "security": [
          {
            "oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ]
          }
        ],
        "description": "Subscribe to a channel"
      },
      "delete": {
        "operationId": "subscriptionsDelete",
        "summary": "Unsubscribe from a channel",
        "tags": [
          "Subscriptions"
        ],
        "security": [
          {
            "oauth2": [
              "https://www.googleapis.com/auth/youtube"
            ]
          }
        ],
        "description": "Unsubscribe from a channel"
      }
    },
    "/videoCategories": {
      "get": {
        "operationId": "videoCategoriesList",
        "summary": "List video categories",
        "tags": [
          "Videos"
        ],
        "description": "List video categories"
      }
    },
    "/captions": {
      "get": {
        "operationId": "captionsList",
        "summary": "List captions for a video",
        "tags": [
          "Captions"
        ],
        "description": "List captions for a video"
      }
    }
  },
  "tags": [
    {
      "name": "Search",
      "description": "Search for content."
    },
    {
      "name": "Videos",
      "description": "Video operations."
    },
    {
      "name": "Channels",
      "description": "Channel operations."
    },
    {
      "name": "Playlists",
      "description": "Playlist operations."
    },
    {
      "name": "Comments",
      "description": "Comment operations."
    },
    {
      "name": "Subscriptions",
      "description": "Subscription operations."
    },
    {
      "name": "Captions",
      "description": "Caption operations."
    }
  ]
}
