{
  "openapi": "3.0.3",
  "info": {
    "title": "Calendar API",
    "version": "v3",
    "description": "Manipulates events and other calendar data.",
    "x-jentic-source-url": "https://developers.google.com/calendar/api",
    "contact": {
      "name": "API Support"
    }
  },
  "servers": [
    {
      "url": "https://www.googleapis.com/calendar/v3"
    }
  ],
  "paths": {
    "/calendars/{calendarId}/acl/{ruleId}": {
      "delete": {
        "operationId": "calendar_acl_delete",
        "summary": "Deletes an access control rule.",
        "description": "Deletes an access control rule.",
        "tags": [
          "Acl"
        ]
      },
      "get": {
        "operationId": "calendar_acl_get",
        "summary": "Returns an access control rule.",
        "description": "Returns an access control rule.",
        "tags": [
          "Acl"
        ]
      },
      "patch": {
        "operationId": "calendar_acl_patch",
        "summary": "Updates an access control rule. This method supports patch semantics.",
        "description": "Updates an access control rule. This method supports patch semantics.",
        "tags": [
          "Acl"
        ]
      },
      "put": {
        "operationId": "calendar_acl_update",
        "summary": "Updates an access control rule.",
        "description": "Updates an access control rule.",
        "tags": [
          "Acl"
        ]
      }
    },
    "/calendars/{calendarId}/acl": {
      "post": {
        "operationId": "calendar_acl_insert",
        "summary": "Creates an access control rule.",
        "description": "Creates an access control rule.",
        "tags": [
          "Acl"
        ]
      },
      "get": {
        "operationId": "calendar_acl_list",
        "summary": "Returns the rules in the access control list for the calendar.",
        "description": "Returns the rules in the access control list for the calendar.",
        "tags": [
          "Acl"
        ]
      }
    },
    "/calendars/{calendarId}/acl/watch": {
      "post": {
        "operationId": "calendar_acl_watch",
        "summary": "Watch for changes to ACL resources.",
        "description": "Watch for changes to ACL resources.",
        "tags": [
          "Acl"
        ]
      }
    },
    "/users/me/calendarList/{calendarId}": {
      "delete": {
        "operationId": "calendar_calendarList_delete",
        "summary": "Removes a calendar from the user's calendar list.",
        "description": "Removes a calendar from the user's calendar list.",
        "tags": [
          "Calendarlist"
        ]
      },
      "get": {
        "operationId": "calendar_calendarList_get",
        "summary": "Returns a calendar from the user's calendar list.",
        "description": "Returns a calendar from the user's calendar list.",
        "tags": [
          "Calendarlist"
        ]
      },
      "patch": {
        "operationId": "calendar_calendarList_patch",
        "summary": "Updates an existing calendar on the user's calendar list. This method supports patch semantics.",
        "description": "Updates an existing calendar on the user's calendar list. This method supports patch semantics.",
        "tags": [
          "Calendarlist"
        ]
      },
      "put": {
        "operationId": "calendar_calendarList_update",
        "summary": "Updates an existing calendar on the user's calendar list.",
        "description": "Updates an existing calendar on the user's calendar list.",
        "tags": [
          "Calendarlist"
        ]
      }
    },
    "/users/me/calendarList": {
      "post": {
        "operationId": "calendar_calendarList_insert",
        "summary": "Inserts an existing calendar into the user's calendar list.",
        "description": "Inserts an existing calendar into the user's calendar list.",
        "tags": [
          "Calendarlist"
        ]
      },
      "get": {
        "operationId": "calendar_calendarList_list",
        "summary": "Returns the calendars on the user's calendar list.",
        "description": "Returns the calendars on the user's calendar list.",
        "tags": [
          "Calendarlist"
        ]
      }
    },
    "/users/me/calendarList/watch": {
      "post": {
        "operationId": "calendar_calendarList_watch",
        "summary": "Watch for changes to CalendarList resources.",
        "description": "Watch for changes to CalendarList resources.",
        "tags": [
          "Calendarlist"
        ]
      }
    },
    "/calendars/{calendarId}/clear": {
      "post": {
        "operationId": "calendar_calendars_clear",
        "summary": "Clears a primary calendar. This operation deletes all events associated with the primary calendar of an account.",
        "description": "Clears a primary calendar. This operation deletes all events associated with the primary calendar of an account.",
        "tags": [
          "Calendars"
        ]
      }
    },
    "/calendars/{calendarId}": {
      "delete": {
        "operationId": "calendar_calendars_delete",
        "summary": "Deletes a secondary calendar. Use calendars.clear for clearing all events on primary calendars.",
        "description": "Deletes a secondary calendar. Use calendars.clear for clearing all events on primary calendars.",
        "tags": [
          "Calendars"
        ]
      },
      "get": {
        "operationId": "calendar_calendars_get",
        "summary": "Returns metadata for a calendar.",
        "description": "Returns metadata for a calendar.",
        "tags": [
          "Calendars"
        ]
      },
      "patch": {
        "operationId": "calendar_calendars_patch",
        "summary": "Updates metadata for a calendar. This method supports patch semantics.",
        "description": "Updates metadata for a calendar. This method supports patch semantics.",
        "tags": [
          "Calendars"
        ]
      },
      "put": {
        "operationId": "calendar_calendars_update",
        "summary": "Updates metadata for a calendar.",
        "description": "Updates metadata for a calendar.",
        "tags": [
          "Calendars"
        ]
      }
    },
    "/calendars": {
      "post": {
        "operationId": "calendar_calendars_insert",
        "summary": "Creates a secondary calendar.\nThe authenticated user for the request is made the data owner of the new calendar.\n\nNote: We recommend to authenticate as the intended data owner of the calendar. You can",
        "description": "Creates a secondary calendar.\nThe authenticated user for the request is made the data owner of the new calendar.\n\nNote: We recommend to authenticate as the intended data owner of the calendar. You can use domain-wide delegation of authority to allow applications to act on behalf of a specific user. Don't use a service account for authentication. If you use a service account for authentication, the service account is the data owner, which can lead to unexpected behavior[...]",
        "tags": [
          "Calendars"
        ]
      }
    },
    "/channels/stop": {
      "post": {
        "operationId": "calendar_channels_stop",
        "summary": "Stop watching resources through this channel",
        "description": "Stop watching resources through this channel",
        "tags": [
          "Channels"
        ]
      }
    },
    "/colors": {
      "get": {
        "operationId": "calendar_colors_get",
        "summary": "Returns the color definitions for calendars and events.",
        "description": "Returns the color definitions for calendars and events.",
        "tags": [
          "Colors"
        ]
      }
    },
    "/calendars/{calendarId}/events/{eventId}": {
      "delete": {
        "operationId": "calendar_events_delete",
        "summary": "Deletes an event.",
        "description": "Deletes an event.",
        "tags": [
          "Events"
        ]
      },
      "get": {
        "operationId": "calendar_events_get",
        "summary": "Returns an event based on its Google Calendar ID. To retrieve an event using its iCalendar ID, call the events.list method using the iCalUID parameter.",
        "description": "Returns an event based on its Google Calendar ID. To retrieve an event using its iCalendar ID, call the events.list method using the iCalUID parameter.",
        "tags": [
          "Events"
        ]
      },
      "patch": {
        "operationId": "calendar_events_patch",
        "summary": "Updates an event. This method supports patch semantics.",
        "description": "Updates an event. This method supports patch semantics.",
        "tags": [
          "Events"
        ]
      },
      "put": {
        "operationId": "calendar_events_update",
        "summary": "Updates an event.",
        "description": "Updates an event.",
        "tags": [
          "Events"
        ]
      }
    },
    "/calendars/{calendarId}/events/import": {
      "post": {
        "operationId": "calendar_events_import",
        "summary": "Imports an event. This operation is used to add a private copy of an existing event to a calendar. Only events with an eventType of default may be imported.\nDeprecated behavior: If a non-default event",
        "description": "Imports an event. This operation is used to add a private copy of an existing event to a calendar. Only events with an eventType of default may be imported.\nDeprecated behavior: If a non-default event is imported, its type will be changed to default and any event-type-specific properties it may have will be dropped.",
        "tags": [
          "Events"
        ]
      }
    },
    "/calendars/{calendarId}/events": {
      "post": {
        "operationId": "calendar_events_insert",
        "summary": "Creates an event.",
        "description": "Creates an event.",
        "tags": [
          "Events"
        ]
      },
      "get": {
        "operationId": "calendar_events_list",
        "summary": "Returns events on the specified calendar.",
        "description": "Returns events on the specified calendar.",
        "tags": [
          "Events"
        ]
      }
    },
    "/calendars/{calendarId}/events/{eventId}/instances": {
      "get": {
        "operationId": "calendar_events_instances",
        "summary": "Returns instances of the specified recurring event.",
        "description": "Returns instances of the specified recurring event.",
        "tags": [
          "Events"
        ]
      }
    },
    "/calendars/{calendarId}/events/{eventId}/move": {
      "post": {
        "operationId": "calendar_events_move",
        "summary": "Moves an event to another calendar, i.e. changes an event's organizer. Note that only default events can be moved; birthday, focusTime, fromGmail, outOfOffice and workingLocation events cannot be move",
        "description": "Moves an event to another calendar, i.e. changes an event's organizer. Note that only default events can be moved; birthday, focusTime, fromGmail, outOfOffice and workingLocation events cannot be moved.",
        "tags": [
          "Events"
        ]
      }
    },
    "/calendars/{calendarId}/events/quickAdd": {
      "post": {
        "operationId": "calendar_events_quickAdd",
        "summary": "Creates an event based on a simple text string.",
        "description": "Creates an event based on a simple text string.",
        "tags": [
          "Events"
        ]
      }
    },
    "/calendars/{calendarId}/events/watch": {
      "post": {
        "operationId": "calendar_events_watch",
        "summary": "Watch for changes to Events resources.",
        "description": "Watch for changes to Events resources.",
        "tags": [
          "Events"
        ]
      }
    },
    "/freeBusy": {
      "post": {
        "operationId": "calendar_freebusy_query",
        "summary": "Returns free/busy information for a set of calendars.",
        "description": "Returns free/busy information for a set of calendars.",
        "tags": [
          "Freebusy"
        ]
      }
    },
    "/users/me/settings/{setting}": {
      "get": {
        "operationId": "calendar_settings_get",
        "summary": "Returns a single user setting.",
        "description": "Returns a single user setting.",
        "tags": [
          "Settings"
        ]
      }
    },
    "/users/me/settings": {
      "get": {
        "operationId": "calendar_settings_list",
        "summary": "Returns all user settings for the authenticated user.",
        "description": "Returns all user settings for the authenticated user.",
        "tags": [
          "Settings"
        ]
      }
    },
    "/users/me/settings/watch": {
      "post": {
        "operationId": "calendar_settings_watch",
        "summary": "Watch for changes to Settings resources.",
        "description": "Watch for changes to Settings resources.",
        "tags": [
          "Settings"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/v2/auth",
            "tokenUrl": "https://oauth2.googleapis.com/token",
            "scopes": {
              "https://www.googleapis.com/auth/calendar": "See, edit, share, and permanently delete all the calendars you can access using Google Calendar",
              "https://www.googleapis.com/auth/calendar.acls": "See and change the sharing permissions of Google calendars you own",
              "https://www.googleapis.com/auth/calendar.acls.readonly": "See the sharing permissions of Google calendars you own",
              "https://www.googleapis.com/auth/calendar.app.created": "Make secondary Google calendars, and see, create, change, and delete events on them",
              "https://www.googleapis.com/auth/calendar.calendarlist": "See, add, and remove Google calendars you’re subscribed to",
              "https://www.googleapis.com/auth/calendar.calendarlist.readonly": "See the list of Google calendars you’re subscribed to",
              "https://www.googleapis.com/auth/calendar.calendars": "See and change the properties of Google calendars you have access to, and create secondary calendars",
              "https://www.googleapis.com/auth/calendar.calendars.readonly": "See the title, description, default time zone, and other properties of Google calendars you have access to",
              "https://www.googleapis.com/auth/calendar.events": "View and edit events on all your calendars",
              "https://www.googleapis.com/auth/calendar.events.freebusy": "See the availability on Google calendars you have access to",
              "https://www.googleapis.com/auth/calendar.events.owned": "See, create, change, and delete events on Google calendars you own",
              "https://www.googleapis.com/auth/calendar.events.owned.readonly": "See the events on Google calendars you own",
              "https://www.googleapis.com/auth/calendar.events.public.readonly": "See the events on public calendars",
              "https://www.googleapis.com/auth/calendar.events.readonly": "View events on all your calendars",
              "https://www.googleapis.com/auth/calendar.freebusy": "View your availability in your calendars",
              "https://www.googleapis.com/auth/calendar.readonly": "See and download any calendar you can access using your Google Calendar",
              "https://www.googleapis.com/auth/calendar.settings.readonly": "View your Calendar settings"
            }
          }
        }
      },
      "apiKey": {
        "type": "apiKey",
        "name": "key",
        "in": "query"
      }
    }
  },
  "security": [
    {
      "oauth2": []
    }
  ],
  "tags": [
    {
      "name": "Acl"
    },
    {
      "name": "Calendarlist"
    },
    {
      "name": "Calendars"
    },
    {
      "name": "Channels"
    },
    {
      "name": "Colors"
    },
    {
      "name": "Events"
    },
    {
      "name": "Freebusy"
    },
    {
      "name": "Settings"
    }
  ]
}
